[default]
domain = "freq"

[default.sound.system]
rate = 48000
data_format = "float32"

[default.sound.system.channels]
input = 2
output = 2

[default.sound.sounddevice]
never_drop_input = true
prime_output_buffers_using_stream_callback = true

[default.sound.target]
main = "speaker"
internal_monitor = "monitor"
field_meter = "array"

[default.filter]
model = "nlms"
mu = 0.1
w = "unit"
length = 10
lambda_ = 1.0
blocksize = 256
window = "hann"
